### ISSUE TITLE
[BUG] Docker container with HOST_DOMAIN is always unhealthy

### ISSUE THREAD

**Issue by iamjackg** [getfider/fider#1047] opened 2022-01-24 22:00 UTC
**Fider Cloud or Self Hosted**
Self hosted, 0.20

**Describe the bug**
The container's healthcheck uses `./fider ping`, which is hardcoded to call `localhost:3000`. If this doesn't match the provided `HOST_DOMAIN`, the check fails and the container is never marked as healthy.

**To Reproduce**
1. Start `getfider/fider:main`

**Expected behavior**
The container is marked as healthy when healthy.

**Comment by goenning** [comment] 2022-01-25 18:35
yeah, that's a good catch. can you try `adding -H "Host: $HOST_DOMAIN"` to your health check to see if that solves?

**Comment by iamjackg** [comment] 2022-01-25 19:03
Oh I'm good, thanks -- I removed the healthcheck altogether by adding the `disable:` key in my compose file since I'm not worried about it. It just caused me some pain because Traefik silently refuses to forward any traffic to a container if it's not healthy.

Just wanted to make you aware. Cheers!

**Comment by gerkevgarderen** [comment] 2022-01-31 18:35
Sadly, adding `-H "Host: $HOST_DOMAIN"` did not work for me. But I believe I found the cause and [created a PR](https://github.com/getfider/fider/pull/1048) with a fix.

**Comment by goenning** [comment] 2022-02-03 19:10
This should be fixed now with the latest `main` image.

**Closed** 2022-02-04 18:44 UTC
Labels: type: bug
