### ISSUE TITLE
[BUG] User-uploaded images fail to load

### ISSUE THREAD

**Issue by Jorys-Paulin** [getfider/fider#998] opened 2021-08-20 13:55 UTC
**Fider Cloud or Self Hosted**
Fider self-hosted, deployed using Docker (on AWS, Ubuntu VM)
Version `0.19.0`, Docker tag `stable` (as per the documentation)

**Describe the bug**
Images that have been uploaded by the user, like user avatar, site logo and OAuth icons, fail to load. The request returns a 404 not found error instead of the expected image.

**To Reproduce**
1. Follow the "deploy with Docker guide" and configure a fresh Fider instance
2. Upload an image as a site logo
3. Save changes and go back to main page
4. See that the logo doesn't load, alt text is displayed instead

**Expected behavior**
The uploaded image should load, instead of displaying alt text

**Screenshots**
![feedback chainejoueur542 fr_](https://user-images.githubusercontent.com/5084309/130243888-ccc3fee9-a802-45b7-9bff-335bba6c17af.png)

**Additional context**
I've first noticed this issue while updating an existing installation (https://ideas.moonlight-stream.org/). I've however created a new instance, separated from the first one (https://feedback.chainejoueur542.fr/) but I still get the same bug.

**Comment by goenning** [comment] 2021-08-21 19:45
Looks like we had a regression on 0.19, can you please try using the getfider/fider:main image? It should be fixed there.

When confirmed I’ll tag as stable

thanks

**Comment by Jorys-Paulin** [comment] 2021-08-21 20:52
Okay, using the `getfider/fider:main` image instead seems to fix the issue, I didn't even need to re-upload the images.

**Comment by Jorys-Paulin** [comment] 2021-08-21 20:52
Okay, using the `getfider/fider:main` image instead seems to fix the issue, I didn't even need to re-upload the images.

**Comment by goenning** [comment] 2021-08-22 18:25
Thanks, I'll tag as stable sometime this week

**Closed by goenning** 2021-08-22 18:25 UTC
Labels: type: bug

**Comment by jendib** [comment] 2021-09-16 16:18
Is this included in 0.19.1? I'm experience the same issue with the version, and on top of not loading it seems to freeze the entire server (no other page is loading) forcing me to reboot the server.

**Comment by Jorys-Paulin** [comment] 2021-09-16 16:29
Hello! It works great on my setup using `getfider/fider:0.19.1`, maybe you need to pull down the image again?

**Comment by jendib** [comment] 2021-09-16 16:36
I did, it's running 0.19.1 for sure. The problem doesn't happen all the time, but I need to restart the server at least once per week. I added a liveness probe on the pod for now so it restart by itself.

**Comment by jldevezas** [comment] 2021-09-30 10:51
I can also confirm that 0.19.1 fixes this issue. I switched the version in docker-compose.yml and ran docker-compose down followed by docker-compose up (my database is part of the system, but I think this also works if it's managed by the container).
